/*  File generated by: Map Ed v0.98.5 */

#include "gba_types.h"

#define MAPHEIGHT 512
#define MAPWIDTH 64

#define bgPalLen 32
extern const u16 bgPalette[256];

#define bgTilesLen 5152
extern const u16 bgTiles[528];

#define bgMapLen 65536
extern const u16 bgMap[32768];

#define bgColLen 32768
extern const u16 bgCollision[32768];
