/*  File generated by: Map Ed v0.99 */

#include "../../../gba/gba_types.h"

#define Map_BIGMap_PaletteLen 16*2
extern const u16 Map_BIGMap_Palette[16];
#define Map_BIGMap_TilesLen 2576*2
extern const u16 Map_BIGMap_Tiles[2576];
#define Map_BIGMap_MapLen 16384*2
extern const u16 Map_BIGMap_Map[16384];
#define Map_BIGMapColLen 16384*2
extern const u16 Map_BIGMap_Col[16384];
