/*  File generated by: Map Ed v0.99 */

#include "../../../gba/gba_types.h"

#define Map_TallMap_PaletteLen 16*2
extern const u16 Map_TallMap_Palette[16];
#define Map_TallMap_TilesLen 528*2
extern const u16 Map_TallMap_Tiles[528];
#define Map_TallMap_MapLen 32768*2
extern const u16 Map_TallMap_Map[32768];
#define Map_TallMapColLen 32768*2
extern const u16 Map_TallMap_Col[32768];
